import { defineMongooseModel } from '#nuxt/mongoose';

export const Corporation = defineMongooseModel('Corporation', {
  clientId: { type: String, required: true },
  name: { type: String, required: true },
  status: { type: String, required: true },
  incorporatedDate: { type: String },
  bnNumber: { type: String },
  federalNo: { type: String },
  isedAccountId: { type: String },
  isedPassword: { type: String },
  federalKey: { type: String },
  provincialNo: { type: String },
  companyKey: { type: String },
  endingPeriod: { type: String },
  contact: { type: String },
  sinNumber: { type: String },
  primaryContact: { type: String },
  mainPhone: { type: String },
  industry: { type: String },
  mainEmail: { type: String },
  oneKeyId: { type: String },
  onePassword: { type: String },
  otherContactPerson: { type: String },
  phone: { type: String },
  wsibNo: { type: String },
  accessCode: { type: String },
  address: { type: String },
  note: { type: String },
  ts: { type: Date, required: true, default: Date.now },
  lts: { type: Date, required: true, default: Date.now },
});